name: flutter_titled_container
description: This widget displayes a title on top of a Container. You can specify the title, titleColor, fontSize and background color for this to display.
version: 1.0.5
homepage: https://github.com/johandb/flutter_titled_container

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
