name: flutter_titled_container
description: A titled container with border
version: 1.0.1
homepage: https://github.com/johandb/flutter_titled_container

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
